package example

// Auto-generated by Mockhiato
import (
	mock "github.com/stretchr/testify/mock"
	net "net"
	time "time"
)

// TargetMock implements example.Target
type TargetMock struct{ mock.Mock }

// Close implements (example.Target).Close
func (r *TargetMock) Close() error {
	ret := r.Called()
	ret0 := ret.Get(0).(error)
	return ret0
}

// LocalAddr implements (example.Target).LocalAddr
func (r *TargetMock) LocalAddr() net.Addr {
	ret := r.Called()
	ret0 := ret.Get(0).(net.Addr)
	return ret0
}

// Read implements (example.Target).Read
func (r *TargetMock) Read(p0 []byte) (int, error) {
	ret := r.Called(p0)
	ret0 := ret.Get(0).(int)
	ret1 := ret.Get(1).(error)
	return ret0, ret1
}

// RemoteAddr implements (example.Target).RemoteAddr
func (r *TargetMock) RemoteAddr() net.Addr {
	ret := r.Called()
	ret0 := ret.Get(0).(net.Addr)
	return ret0
}

// SetDeadline implements (example.Target).SetDeadline
func (r *TargetMock) SetDeadline(p0 time.Time) error {
	ret := r.Called(p0)
	ret0 := ret.Get(0).(error)
	return ret0
}

// SetReadDeadline implements (example.Target).SetReadDeadline
func (r *TargetMock) SetReadDeadline(p0 time.Time) error {
	ret := r.Called(p0)
	ret0 := ret.Get(0).(error)
	return ret0
}

// SetWriteDeadline implements (example.Target).SetWriteDeadline
func (r *TargetMock) SetWriteDeadline(p0 time.Time) error {
	ret := r.Called(p0)
	ret0 := ret.Get(0).(error)
	return ret0
}

// Write implements (example.Target).Write
func (r *TargetMock) Write(p0 []byte) (int, error) {
	ret := r.Called(p0)
	ret0 := ret.Get(0).(int)
	ret1 := ret.Get(1).(error)
	return ret0, ret1
}
