package mnet

// Code generated by Mockhiato. DO NOT EDIT.
import (
	mock "github.com/stretchr/testify/mock"
	net "net"
	time "time"
)

// NewAddrMock creates a new AddrMock
func NewAddrMock() *AddrMock { return &AddrMock{} }

// AddrMock implements mnet.Addr
type AddrMock struct{ mock.Mock }

// Network implements (mnet.Addr).Network
func (r *AddrMock) Network() string {
	ret := r.Called()
	var ret0 string
	if a := ret.Get(0); a != nil {
		ret0 = a.(string)
	}
	return ret0
}

// String implements (mnet.Addr).String
func (r *AddrMock) String() string {
	ret := r.Called()
	var ret0 string
	if a := ret.Get(0); a != nil {
		ret0 = a.(string)
	}
	return ret0
}

// NewConnMock creates a new ConnMock
func NewConnMock() *ConnMock { return &ConnMock{} }

// ConnMock implements mnet.Conn
type ConnMock struct{ mock.Mock }

// Close implements (mnet.Conn).Close
func (r *ConnMock) Close() error {
	ret := r.Called()
	var ret0 error
	if a := ret.Get(0); a != nil {
		ret0 = a.(error)
	}
	return ret0
}

// LocalAddr implements (mnet.Conn).LocalAddr
func (r *ConnMock) LocalAddr() net.Addr {
	ret := r.Called()
	var ret0 net.Addr
	if a := ret.Get(0); a != nil {
		ret0 = a.(net.Addr)
	}
	return ret0
}

// Read implements (mnet.Conn).Read
func (r *ConnMock) Read(p0 []byte) (int, error) {
	ret := r.Called(p0)
	var ret0 int
	if a := ret.Get(0); a != nil {
		ret0 = a.(int)
	}
	var ret1 error
	if a := ret.Get(1); a != nil {
		ret1 = a.(error)
	}
	return ret0, ret1
}

// RemoteAddr implements (mnet.Conn).RemoteAddr
func (r *ConnMock) RemoteAddr() net.Addr {
	ret := r.Called()
	var ret0 net.Addr
	if a := ret.Get(0); a != nil {
		ret0 = a.(net.Addr)
	}
	return ret0
}

// SetDeadline implements (mnet.Conn).SetDeadline
func (r *ConnMock) SetDeadline(p0 time.Time) error {
	ret := r.Called(p0)
	var ret0 error
	if a := ret.Get(0); a != nil {
		ret0 = a.(error)
	}
	return ret0
}

// SetReadDeadline implements (mnet.Conn).SetReadDeadline
func (r *ConnMock) SetReadDeadline(p0 time.Time) error {
	ret := r.Called(p0)
	var ret0 error
	if a := ret.Get(0); a != nil {
		ret0 = a.(error)
	}
	return ret0
}

// SetWriteDeadline implements (mnet.Conn).SetWriteDeadline
func (r *ConnMock) SetWriteDeadline(p0 time.Time) error {
	ret := r.Called(p0)
	var ret0 error
	if a := ret.Get(0); a != nil {
		ret0 = a.(error)
	}
	return ret0
}

// Write implements (mnet.Conn).Write
func (r *ConnMock) Write(p0 []byte) (int, error) {
	ret := r.Called(p0)
	var ret0 int
	if a := ret.Get(0); a != nil {
		ret0 = a.(int)
	}
	var ret1 error
	if a := ret.Get(1); a != nil {
		ret1 = a.(error)
	}
	return ret0, ret1
}
