language: go

go:
  - 1.7
  - 1.7.1
  - 1.7.3
  - 1.7.4
  - 1.7.5
  - 1.8
  - 1.8.1
  # - stable # https://travis-ci.org/littledot/mockhiato/jobs/228108737 stable is down
  - master

go_import_path: sdchang.com/mockhiato

script:
  - go test -v ./...

notifications:
  slack:
    rooms:
      - mockhiato:ADHPhjuApyXvWh4OKFYs0Hrx#bot-travis
