language: go

go:
  - "1.7"
  - "1.7.1"
  - "1.7.3"
  - "1.7.4"
  - "1.7.5"
  - "1.8"
  - "1.8.1"
  - "1.8.2"
  - "1.8.3"
  - "1.9"
  - "1.9.1"
  - "1.9.2"
  - "1.9.3"
  - "1.9.4"
  - "1.9.5"
  - "1.10"
  - "1.10.1"
  - stable
  - master

matrix:
  allow_failures:
    - go: master

script:
  - ./cmd/cover_multiple_packages.sh
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - ./cmd/go_report_card.sh

notifications:
  slack:
    secure: ba3+76qMlbhVgJTiSfqWu7xZFkMOgtYGk0cwD4cUvbNlGbi8PeoYnw24SYCvifLE6TyEdDs09HVIEtPEmL8fmXuy5SV/en2WYYWcxaofnxg9wrkF0tpu7rVqlK+Va2o1kvJGW/qDOFhLcQ+t1DjZ5q4pDGUQIQ/sczyg+W7GzQgvDNQsR+onvpf9BEdpXXpT1jDsHeViCJbp122g6y7vBLlnHXCjhIBmfDRxTh/Aj2KRtfbaI5PmX44joMc4EcA7wqFL4lklttiCu2i2kuCIZnvy93+wBopdTU31a8DT7XjkW4+vDBtINu530uh10S47obyuA5S2Jv9WnZF4WQJCVUoRQd44xBOqQLcRmJ8Lqda7XUQm1yPoZgzmTLmydZ4zzSlFnEVgIqmWAKX1d/DwtsQsV/QitUjYoZ8gM6exJFM+nqaSYN38Nqte4B5ydCotFdzA1YLztPJoZgLJzFl7DCv4UXNvV0dvfeu6ZNFcRHYw4zruVn1eyT6ZEu3aVnSTAwka42YEQ3/ESU+onWKv91uHOBp0ivqPtw1drveQ5wTHHf7Yi9THfH/tugrwa8m7YRTvR789YkO4KRvcRo3gl2FrVXdzpvXh3TBz/oQkuYVm/tTLg9pbGV2YI1Q+gW7EnfNZJMCRoHHgaV/Oz8nnzr4ar7/jsfLOb6+2cY6MIVA=
