language: go

go:
  # - 1.7.x # undefined: sort.Slice
  - 1.8.x
  # - stable # https://travis-ci.org/littledot/mockhiato/jobs/228108737 stable is down
  - master

go_import_path: sdchang.com/mockhiato

script:
  - go test -v ./...
