package mocks

// Auto-generated by Mockhiato
import (
	bigdot "gitgud.com/bigdot"
	mock "github.com/stretchr/testify/mock"
	os "os"
	time "time"
)

// FileInfoMock implements mocks.FileInfo
type FileInfoMock struct{ mock.Mock }

// IsDir implements (mocks.FileInfo).IsDir
func (r *FileInfoMock) IsDir() bool {
	ret := r.Called()
	var ret0 bool
	if a := ret.Get(0); a != nil {
		ret0 = a.(bool)
	}
	return ret0
}

// ModTime implements (mocks.FileInfo).ModTime
func (r *FileInfoMock) ModTime() time.Time {
	ret := r.Called()
	var ret0 time.Time
	if a := ret.Get(0); a != nil {
		ret0 = a.(time.Time)
	}
	return ret0
}

// Mode implements (mocks.FileInfo).Mode
func (r *FileInfoMock) Mode() os.FileMode {
	ret := r.Called()
	var ret0 os.FileMode
	if a := ret.Get(0); a != nil {
		ret0 = a.(os.FileMode)
	}
	return ret0
}

// Name implements (mocks.FileInfo).Name
func (r *FileInfoMock) Name() string {
	ret := r.Called()
	var ret0 string
	if a := ret.Get(0); a != nil {
		ret0 = a.(string)
	}
	return ret0
}

// Size implements (mocks.FileInfo).Size
func (r *FileInfoMock) Size() int64 {
	ret := r.Called()
	var ret0 int64
	if a := ret.Get(0); a != nil {
		ret0 = a.(int64)
	}
	return ret0
}

// Sys implements (mocks.FileInfo).Sys
func (r *FileInfoMock) Sys() interface{} {
	ret := r.Called()
	var ret0 interface{}
	if a := ret.Get(0); a != nil {
		ret0 = a.(interface{})
	}
	return ret0
}

// VendorDepMock implements mocks.VendorDep
type VendorDepMock struct{ mock.Mock }

// Vending implements (mocks.VendorDep).Vending
func (r *VendorDepMock) Vending(p0 bigdot.VendorStruct) {
	r.Called(p0)
	return
}

// errorMock implements mocks.error
type errorMock struct{ mock.Mock }

// Error implements (mocks.error).Error
func (r *errorMock) Error() string {
	ret := r.Called()
	var ret0 string
	if a := ret.Get(0); a != nil {
		ret0 = a.(string)
	}
	return ret0
}
