package example

// Code generated by Mockhiato. DO NOT EDIT.
import (
	mock "github.com/stretchr/testify/mock"
)

// NewTypeAliasMock creates a new TypeAliasMock
func NewTypeAliasMock() *TypeAliasMock { return &TypeAliasMock{} }

// TypeAliasMock implements example.TypeAlias
type TypeAliasMock struct{ mock.Mock }

// Read implements (example.TypeAlias).Read
func (r *TypeAliasMock) Read(p0 []byte) (int, error) {
	ret := r.Called(p0)
	var ret0 int
	if a := ret.Get(0); a != nil {
		ret0 = a.(int)
	}
	var ret1 error
	if a := ret.Get(1); a != nil {
		ret1 = a.(error)
	}
	return ret0, ret1
}
