package example

// Code generated by Mockhiato. DO NOT EDIT.
import (
	driver "database/sql/driver"
	flag "flag"
	mock "github.com/stretchr/testify/mock"
	constant "go/constant"
	os "os"
)

// NewBMock creates a new BMock
func NewBMock() *BMock { return &BMock{} }

// BMock implements example.B
type BMock struct{ mock.Mock }

// NewTargetMock creates a new TargetMock
func NewTargetMock() *TargetMock { return &TargetMock{} }

// TargetMock implements example.Target
type TargetMock struct{ mock.Mock }

// DefineAndUse implements (example.Target).DefineAndUse
func (r *TargetMock) DefineAndUse(p0 B) {
	r.Called(p0)
	return
}

// GoInterface implements (example.Target).GoInterface
func (r *TargetMock) GoInterface(p0 os.FileInfo) error {
	ret := r.Called(p0)
	var ret0 error
	if a := ret.Get(0); a != nil {
		ret0 = a.(error)
	}
	return ret0
}

// InterfaceWithSameName implements (example.Target).InterfaceWithSameName
func (r *TargetMock) InterfaceWithSameName(p0 flag.Value) {
	r.Called(p0)
	return
}

// InterfaceWithSameName2 implements (example.Target).InterfaceWithSameName2
func (r *TargetMock) InterfaceWithSameName2(p0 driver.Value) {
	r.Called(p0)
	return
}

// InterfaceWithSameName3 implements (example.Target).InterfaceWithSameName3
func (r *TargetMock) InterfaceWithSameName3(p0 constant.Value) {
	r.Called(p0)
	return
}
