package mocks

// Code generated by Mockhiato. DO NOT EDIT.
import (
	mock "github.com/stretchr/testify/mock"
)

// NewerrorMock creates a new errorMock
func NewerrorMock() *errorMock { return &errorMock{} }

// errorMock implements mocks.error
type errorMock struct{ mock.Mock }

// Error implements (mocks.error).Error
func (r *errorMock) Error() string {
	ret := r.Called()
	var ret0 string
	if a := ret.Get(0); a != nil {
		ret0 = a.(string)
	}
	return ret0
}
