package mtools

// Code generated by Mockhiato. DO NOT EDIT.
import (
	mock "github.com/stretchr/testify/mock"
	tools "golang.org/x/tools"
)

// NewVendorDepMock creates a new VendorDepMock
func NewVendorDepMock() *VendorDepMock { return &VendorDepMock{} }

// VendorDepMock implements mtools.VendorDep
type VendorDepMock struct{ mock.Mock }

// Vending implements (mtools.VendorDep).Vending
func (r *VendorDepMock) Vending(p0 tools.VendorStruct) {
	r.Called(p0)
	return
}
