package massert

// Code generated by Mockhiato. DO NOT EDIT.
import (
	mock "github.com/stretchr/testify/mock"
)

// NewTestingTMock creates a new TestingTMock
func NewTestingTMock() *TestingTMock { return &TestingTMock{} }

// TestingTMock implements massert.TestingT
type TestingTMock struct{ mock.Mock }

// Errorf implements (massert.TestingT).Errorf
func (r *TestingTMock) Errorf(p0 string, p1 ...interface{}) {
	r.Called(p0, p1)
	return
}
