package example

// Code generated by Mockhiato. DO NOT EDIT.
import (
	mock "github.com/stretchr/testify/mock"
	text "golang.org/x/text"
	tools "golang.org/x/tools"
	os "os"
)

// NewBMock creates a new BMock
func NewBMock() *BMock { return &BMock{} }

// BMock implements example.B
type BMock struct{ mock.Mock }

// NewTargetMock creates a new TargetMock
func NewTargetMock() *TargetMock { return &TargetMock{} }

// TargetMock implements example.Target
type TargetMock struct{ mock.Mock }

// DefineAndUse implements (example.Target).DefineAndUse
func (r *TargetMock) DefineAndUse(p0 B) {
	r.Called(p0)
	return
}

// GoInterface implements (example.Target).GoInterface
func (r *TargetMock) GoInterface(p0 os.FileInfo) error {
	ret := r.Called(p0)
	var ret0 error
	if a := ret.Get(0); a != nil {
		ret0 = a.(error)
	}
	return ret0
}

// VendorInterface implements (example.Target).VendorInterface
func (r *TargetMock) VendorInterface(p0 text.VendorDep) {
	r.Called(p0)
	return
}

// VendorInterfaceWithSameName implements (example.Target).VendorInterfaceWithSameName
func (r *TargetMock) VendorInterfaceWithSameName(p0 tools.VendorDep) {
	r.Called(p0)
	return
}
