package example

// Auto-generated by Mockhiato
import (
	bigdot "gitgud.com/bigdot"
	mock "github.com/stretchr/testify/mock"
	os "os"
)

// BMock implements example.B
type BMock struct{ mock.Mock }

// TargetMock implements example.Target
type TargetMock struct{ mock.Mock }

// DefineAndUse implements (example.Target).DefineAndUse
func (r *TargetMock) DefineAndUse(p0 B) {
	r.Called(p0)
	return
}

// GoInterface implements (example.Target).GoInterface
func (r *TargetMock) GoInterface(p0 os.FileInfo) error {
	ret := r.Called(p0)
	var ret0 error
	if a := ret.Get(0); a != nil {
		ret0 = a.(error)
	}
	return ret0
}

// VendorInterface implements (example.Target).VendorInterface
func (r *TargetMock) VendorInterface(p0 bigdot.VendorDep) {
	r.Called(p0)
	return
}
