package lib

const (
	// Magic is the string used to identify files generated by Mockhiato.
	Magic = "// Code generated by Mockhiato. DO NOT EDIT."
	// InterfaceNameToken is a placeholder used in configs.
	InterfaceNameToken = "{interface}"
	// PackageNameToken is a placeholder used in configs.
	PackageNameToken = "{package}"
)
