package mdriver

// Code generated by Mockhiato. DO NOT EDIT.
import (
	mock "github.com/stretchr/testify/mock"
)

// NewValueMock creates a new ValueMock
func NewValueMock() *ValueMock { return &ValueMock{} }

// ValueMock implements mdriver.Value
type ValueMock struct{ mock.Mock }
