package mbigdot

// Code generated by Mockhiato. DO NOT EDIT.
import (
	bigdot "gitgud.com/bigdot"
	mock "github.com/stretchr/testify/mock"
)

// NewVendorDepMock creates a new VendorDepMock
func NewVendorDepMock() *VendorDepMock { return &VendorDepMock{} }

// VendorDepMock implements mbigdot.VendorDep
type VendorDepMock struct{ mock.Mock }

// Vending implements (mbigdot.VendorDep).Vending
func (r *VendorDepMock) Vending(p0 bigdot.VendorStruct) {
	r.Called(p0)
	return
}
