package mtext

// Code generated by Mockhiato. DO NOT EDIT.
import (
	mock "github.com/stretchr/testify/mock"
	text "golang.org/x/text"
)

// NewVendorDepMock creates a new VendorDepMock
func NewVendorDepMock() *VendorDepMock { return &VendorDepMock{} }

// VendorDepMock implements mtext.VendorDep
type VendorDepMock struct{ mock.Mock }

// Vending implements (mtext.VendorDep).Vending
func (r *VendorDepMock) Vending(p0 text.VendorStruct) {
	r.Called(p0)
	return
}
