package example

// Auto-generated by Mockhiato
import (
	same "github.com/littledot/mockhiato/test/same_import_name/expect/same"
	same1 "github.com/littledot/mockhiato/test/same_import_name/expect/same1"
	mock "github.com/stretchr/testify/mock"
)

// TargetMock implements example.Target
type TargetMock struct{ mock.Mock }

// A implements (example.Target).A
func (r *TargetMock) A(p0 same.ThisInt, p1 same1.ThatInt) {
	r.Called(p0, p1)
	return
}
