package mflag

// Code generated by Mockhiato. DO NOT EDIT.
import (
	mock "github.com/stretchr/testify/mock"
)

// NewValueMock creates a new ValueMock
func NewValueMock() *ValueMock { return &ValueMock{} }

// ValueMock implements mflag.Value
type ValueMock struct{ mock.Mock }

// Set implements (mflag.Value).Set
func (r *ValueMock) Set(p0 string) error {
	ret := r.Called(p0)
	var ret0 error
	if a := ret.Get(0); a != nil {
		ret0 = a.(error)
	}
	return ret0
}

// String implements (mflag.Value).String
func (r *ValueMock) String() string {
	ret := r.Called()
	var ret0 string
	if a := ret.Get(0); a != nil {
		ret0 = a.(string)
	}
	return ret0
}
