package example

// Code generated by Mockhiato. DO NOT EDIT.
import (
	same "github.com/littledot/mockhiato/lib/generate/test/same_import_name/expect/same"
	same1 "github.com/littledot/mockhiato/lib/generate/test/same_import_name/expect/same1"
	mock "github.com/stretchr/testify/mock"
)

// NewTargetMock creates a new TargetMock
func NewTargetMock() *TargetMock { return &TargetMock{} }

// TargetMock implements example.Target
type TargetMock struct{ mock.Mock }

// A implements (example.Target).A
func (r *TargetMock) A(p0 same.ThisInt, p1 same1.ThatInt) {
	r.Called(p0, p1)
	return
}
